### ISSUE TITLE
下载 OIT-1.3.0 插件压缩包被 WD 报病毒直接删除了

### ISSUE THREAD

**Issue by N0rmaI** [ccseer/Seer-Feedback-CN#4]
电脑版本是win11 24h2，对于OIT-1.3.0 插件压缩包，edge浏览器直接下载说有病毒然后失败，手机下载传输到电脑上会被Windows Defender直接报病毒然后删除，真的服了微软

**Comment by ccseer** [comment]
我找时间看看吧。
刚把 网站改成 https 了。 估计给 exe 加个签名也能解决

**Comment by ccseer** [comment]
- 即使没有代码签名证书，Windows 的 SmartScreen 过滤器会根据应用程序的下载量和使用量逐渐建立信任。如果您的应用程序用户较多，SmartScreen 可能会逐渐减少安全警告。
- 这种方法需要时间积累，并且在软件发布初期用户会看到安全警告

**Comment by ccseer** [comment]
> 我找时间看看吧。 刚把 网站改成 https 了。 估计给 exe 加个签名也能解决

还是算了，都要钱。负担不起 :(
