### ISSUE TITLE
预览avif图片文件缩放有问题

### ISSUE THREAD

**Issue by ririliu** [ccseer/Seer-Feedback-CN#5]
avif预览时缩放貌似固定在100%，不能适应窗口或者适应宽度，也无法手动放大/缩小，这些avif文件是我自己用avifenc编码的，应该没什么特殊的数据
Seer版本：3.3.0
OS：win 10

**Comment by ccseer** [comment]
发个图片我试下

**Comment by ririliu** [comment]
http://dfire-download.oss-accelerate.aliyuncs.com/temp/Sony_a7R5_0410207578.avif

**Comment by ccseer** [comment]
fixed in 4.0.0
![img_v3_02i3_40b85072-be22-40a9-84f2-12485425094g](https://github.com/user-attachments/assets/bbf62ea7-3c74-4a11-83e3-724737effce0)
