### ISSUE TITLE
更新到Seer3.31版后不能打开（win11 24H2）

### ISSUE THREAD

**Issue by liuzunda** [ccseer/Seer-Feedback-CN#7]
更新到Seer3.31版后不能打开（win11 24H2）

**Comment by ccseer** [comment]
打开什么？软件？文件？

**Comment by ccseer** [comment]
![image](https://github.com/user-attachments/assets/24781c74-27e5-4dc3-b4ac-64062ac20fb3)


能不能发一下日志

**Comment by ccseer** [comment]
已修复

**Comment by ccseer** [comment]
请检查更新
