### ISSUE TITLE
快捷键使用出现问题

### ISSUE THREAD

**Issue by DIF31209** [ccseer/Seer-Feedback-CN#8]
更新至3.3.1及3.3.2之后，在使用快捷键方面出现问题。
经过测试，具体表现为：使用Ctrl+空格、Ctrl+Alt+空格预览文件时若文件处于选定状态，则会取消选定并进入预览，此时为文件夹详情预览；若文件处于未选定状态，则会选定文件并进入预览，此时为选定文件的预览。
Shift+空格、Ctrl+Shift+空格、Ctrl+Shift+Alt+空格未出现问题，响应逻辑正确。
Alt+空格、Shift+Alt+空格的快捷键无法使用。

程序版本：3.3.1及3.3.2。
系统版本：Win10 22H2

**Comment by ccseer** [comment]
好的。
应该会改回 焦点 响应。
☑️ 不太好使

**Comment by ccseer** [comment]
你要不要测试下这个？ 没问题的话我就发布了
 https://github.com/ccseer/Seer-Feedback-CN/releases/download/test/Seer-3.3.3.exe

**Comment by ccseer** [comment]
released
