### ISSUE TITLE
图片文件的名称是"@2x"或者"@3x"之类结尾为啥会进行特殊处理？

### ISSUE THREAD

**Issue by ririliu** [ccseer/Seer-Feedback-CN#9]
带"@2x"结尾的图片预览大小是图片实际大小的1/2（宽度和高度都是1/2），带"@3x"结尾的就是1/3，为啥会有这样的特殊处理？

**Comment by ccseer** [comment]
不是特殊处理， 是图片 是高分辨率的，但是程序没有特殊处理这个分辨率。

**Comment by ririliu** [comment]
好像没理解我说的，我给你个例子，有个图片文件，原始文件名是a.jpg，宽度1920px，高度1280px，这时候用seer预览，效果是这样的：
![图片](https://github.com/user-attachments/assets/8b580125-f7b4-4a5f-b938-4c1d3fdec0e1)
预览窗口里显示的图片宽度高度和图片文件的宽度高度一致没有问题；

然后我把图片文件重命名为a@2x.jpg，现在用seer预览，效果是这样的：
![图片](https://github.com/user-attachments/assets/633dc272-0ab1-4748-9b2c-4eba72760a90)
seer窗口的宽度和高度和刚才其实一样还是1920px和1280px，但是其中显示的图片的宽度和高度只有960px和640px，是实际宽度和高度的1/2，整个显示的像素面积就是1/4；

同理，继续把图片文件重命名为a@4x.jpg，然后用seer预览，效果是这样的：
![图片](https://github.com/user-attachments/assets/f7fe693c-11fa-487f-9944-1a93b9209c88)
宽度高度都变成了1/4，显示面积就是1/16

**Comment by ccseer** [comment]
哦，我不知道 文件名 也可以影响。 

目前的情况就是没有处理高分辨率的图片。 你这里改文件名 应该也是被程序当成高分辨率的图片了。

下个大版本可能会改下这个。

**Comment by ririliu** [comment]
你说的高分辨率是指什么？是像素多，还是dpi高？一般在屏幕上查看图片的软件不需要关注图片的dpi信息吧，应该只有打印/印刷流程或者印前的软打样之类的步骤需要按dpi来显示图片，图片预览工具我感觉完全不需要关注dpi信息

**Comment by ccseer** [comment]
<img width="710" alt="image" src="https://github.com/user-attachments/assets/409278c3-785e-4cfc-bb15-0e3209b42747">


缩放

**Comment by ririliu** [comment]
这些是移动端应用为了适配不同分辨率屏幕提供了多套图片资源文件，个人感觉图片预览工具完全不需要考虑这些，不管是dpi也好scale也好，不管你名称里是2x还是3x还是Nx，只需要按像素来显示图片就够了，其他软件也都是这样的，Photoshop、Lightroom、XnView、ACDSee，不会因为图片文件名称里带个@nx就对图片的显示大小进行一番特殊处理

**Comment by ccseer** [comment]
fixed in 4.0.0
![img_v3_02i3_8ed87dae-bd0b-42a5-bd41-22ed96e7728g](https://github.com/user-attachments/assets/6bdea544-3a2b-4783-a083-0c583fd945b2)
